### ISSUE TITLE
Extract an apt resource-mapper to encapsulate the protocol

### ISSUE THREAD

**Issue by jsirois** [twitter/commons#319]
Pants defines a protocol for compiler plugins that emit non-classfiles/non-sourcefiles - generally resources.  The [CmdLineProcessor](https://github.com/twitter/commons/blob/master/src/java/com/twitter/common/args/apt/CmdLineProcessor.java) [now implements](https://github.com/twitter/commons/issues/208) the protocol in an ad-hoc way.  The core emitter should be extracted and published to help centralize the protocol for other annotation processors to use more easily and in a more foolproof manner.

**Comment by stuhood** [comment]
No longer necessary due to isolated compile.
