### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by dt** [twitter/commons#330]
Would be nice to have a README section or a CONTRIBUTING file describing any particular processes for contributing changes (eg rbcommons reviews).

https://github.com/blog/1184-contributing-guidelines

**Comment by Yasumoto** [comment]
Yep, definitely agreed. Anyone that wants to give this a go can use the [pantsbuild contributors guidelines](http://pantsbuild.github.io/howto_contribute.html) as a basis.

**Comment by Yasumoto** [comment]
Out for review at https://rbcommons.com/s/twitter/r/2356/

**Comment by Yasumoto** [comment]
This has been committed in 4451ae98d26713c49a1ea532daef06aba7c38a11
