### ISSUE TITLE
Fail to build thrift package after 0.0.68

### ISSUE THREAD

**Issue by YiuTerran** [twitter/commons#346]
when i build 0.0.69-0.0.72 using maven, it tells me 

>Could not resolve dependencies for project...
>Could not find artifact com.twitter.common:service-thrift:jar".

And the verison number are `0.0.3`, `0.2.1` and `0.2.2`, i definitely can't find these versions of `service-thrift` package in repo `maven.twttr.com`. Did i do something wrong?

**Comment by Yasumoto** [comment]
@YiuTerran Any chance you can re-paste the full command+output while prepending "PANTS_VERBOSE=1" ?

**Comment by YiuTerran** [comment]
I did not try to build it myself. Actually, i added the following to my maven project `pom.xml` file:
```xml
    <repositories>
        <repository>
            <id>twitter-twttr</id>
            <url>http://maven.twttr.com</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>twitter-twttr</id>
            <url>http://maven.twttr.com</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
...
        <dependency>
            <groupId>com.twitter.common</groupId>
            <artifactId>thrift</artifactId>
            <version>0.0.68</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-jdk14</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
...
```
Then i build the project with `mvn compile`, if `verison` for thrift is `0.0.68`, nothing wrong. But when i change it to `0.0.69` - `0.0.72`, it fails. For example, `0.0.72` will output the following:

>Downloading: http://maven.twttr.com/com/twitter/common/service-thrift/0.2.2/service-thrift-0.2.2.pom
Downloading: http://repo.maven.apache.org/maven2/com/twitter/common/service-thrift/0.2.2/service-thrift-0.2.2.pom
[WARNING] The POM for com.twitter.common:service-thrift:jar:0.2.2 is missing, no dependency information available
Downloading: http://maven.twttr.com/com/twitter/common/service-thrift/0.2.2/service-thrift-0.2.2.jar
Downloading: http://repo.maven.apache.org/maven2/com/twitter/common/service-thrift/0.2.2/service-thrift-0.2.2.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.134s
[INFO] Finished at: Thu Jan 15 10:31:35 CST 2015
[INFO] Final Memory: 11M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project news-push: Could not resolve dependencies for project news.dolphin:news-push:war:1.0.0dev: Could not find artifact com.twitter.common:service-thrift:jar:0.2.2 in twitter-twttr (http://maven.twttr.com) -> [Help 1]

That's all.

**Comment by Yasumoto** [comment]
@YiuTerran thanks for reporting! I brought this up to both @jcohen and @stuhood, and they helped isolate the issue. @stuhood is going to publish service-thrift-0.2.2.

**Comment by stuhood** [comment]
@YiuTerran What are the root packages you are depending on? It looks like external publishing for a few targets was disabled during an automated refactor, so I'd like to ensure that everything you're looking for is re-enabled in one go.

Sorry for the trouble!

**Comment by YiuTerran** [comment]
@stuhood In my project, the root package related to `twiiter-commons` is just `thrift`. No others are used.

**Comment by stuhood** [comment]
@YiuTerran : I've gone ahead and re-published these artifacts:

    com.twitter.common#application-action;Semver(0.0.83)
    com.twitter.common#base;Semver(0.0.105)
    com.twitter.common#collections;Semver(0.0.101)
    com.twitter.common#dynamic-host-set;Semver(0.0.50)
    com.twitter.common#jdk-logging;Semver(0.0.72)
    com.twitter.common#net-pool;Semver(0.0.63)
    com.twitter.common#net-util;Semver(0.0.92)
    com.twitter.common#quantity;Semver(0.0.92)
    com.twitter.common#service-thrift;Semver(1.0.53)
    com.twitter.common#stat-registry;Semver(0.0.48)
    com.twitter.common#stat;Semver(0.0.61)
    com.twitter.common#stats-provider;Semver(0.0.84)
    com.twitter.common#stats;Semver(0.0.106)
    com.twitter.common#thrift;Semver(0.0.73)
    com.twitter.common#util-executor-service-shutdown;Semver(0.0.60)
    com.twitter.common#util-sampler;Semver(0.0.71)
    com.twitter.common#util-system-mocks;Semver(0.0.95)
    com.twitter.common#util;Semver(0.0.112)

Thanks for the report!

**Comment by destitutus** [comment]
Hello @stuhood . Was this issue resolved?
I don't see published version of `com.twitter.common:service-thrift:0.2.19` in http://maven.twttr.com/com/twitter/common/service-thrift/
I am trying to use `com.twitter.common:thrift:0.0.79` and it is compiling with error
```
> Could not resolve com.twitter.common:service-thrift:0.2.19.
  Required by:
       > com.twitter.common:thrift:0.0.79
````

works only on `com.twitter.common:thrift:0.0.54` (it looks as very old version). any chance to publish artefacts?
