### ISSUE TITLE
Upgrade python thrift dependency from 0.9.1 to 0.9.2

### ISSUE THREAD

**Issue by jsirois** [twitter/commons#392]
This is motivated by https://issues.apache.org/jira/browse/AURORA-1083.

Thrift 0.9.2 is the latest and the compiler contains many bugfixes, but of interest in python support in particular is python3 support.

The dep should be upgraded with a deprecation cycle to allow those with pinned deps on thrift 0.9.1 a window to upgrade without undue disruption.

**Comment by Yasumoto** [comment]
Oof, this is gonna ~hurt. Thanks for doing this!

**Comment by jsirois** [comment]
@Yasumoto can I assign a publish of t.c python over to you or does @wickman hold the keys to that.  The packages are owned by 'twitter' and I'm not sure who has access to that account.

**Comment by Yasumoto** [comment]
The creds are available to many, and I am one of those. I'll try to get a new dist uploaded before the weekend, but someone else feel free to beat me to it.

**Comment by jsirois** [comment]
Thanks @Yasumoto - I filed #401 for the release and assigned to you for completions or re-assignment.
